# -*- coding: utf-8 -*-
"""ShoeScraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZA_0Bpb2qP8KOzZ2Xvqvx1Nikda24mvz
"""

import requests 
import shutil
import pandas as pd
from google.colab import files
import csv
!pip install pycurl
import os

from google.colab import drive
drive.mount('/content/gdrive')

wbname=["nunnbush","bogsfootwear","stacyadams"]

for zzzz in wbname:
  with open('/content/'+zzzz+'.csv', 'r') as f:
    str_list = [row[0] for row in csv.reader(f)]
    print(str_list)
  p=[]
  retry=[]
  for i in str_list:
    filename=i
    k=i.split("/")
    p.append(k)
    name=k[-2]+"-"+k[-1]
    foldername=k[-2]
    r = requests.get(i,stream=True,verify=False)
    if r.status_code == 200:
      path='/content/gdrive/My Drive/fiverr/1/'+(zzzz.split('.')[0])
      spath=path+'/'+k[-2]
      if not os.path.exists(spath):
        os.makedirs(spath)
      open(path+'/'+foldername+'/'+name, 'wb').write(r.content)
    # files.download(name)
      print('Image sucessfully Downloaded: ',name)
    else:
      retry.append(i)
      print('Image Couldn\'t be retreived')

!zip -r /content/gdrive/My\ Drive/fiverr/1.zip /content/gdrive/My\ Drive/fiverr/1/

